### ISSUE TITLE
[a11y] Move focus inside the modal when it opens, move it back when it closes

### ISSUE THREAD

**Issue by flarnie-chegg** [catcarbonell/popop#2]
**What:** When the modal opens, move the focus to some element inside the modal. Then when it closes, put it back where it used to be.
**Why:** If we don't update focus, then a keyboard user is stuck in the background page and may not be able to get into the modal to activate buttons. Screen reader users likewise will not be alerted to the modal opening and will be stuck in the background. And if the modal closes with focus inside, then the focus gets "lost", putting them in a buggy state.
**How:**
1. Inside you 'open modal' function, before opening the modal, save a reference to the element that currently has focus. With something like `savedTrigger = document.activeElement`.
2. After opening the modal, find the first focusable element inside the modal and set the focus there. Something like this: 
```
const modal = document.getElementById(`${modalId}`);
const focusableChild = modal.querySelector('a, button, input, select, textarea, [contenteditable]');
if (focusableChild) {
  focusableChild.focus();
} else {
  console.warn('Warning! Your modal is not accessible. We need an element to receive focus after the modal opens.')
}
```
3. When the modal is closing, call focus on the `savedTrigger` element. Would need to verify that it still exists in the DOM.

**Source:** Accessibility Features 2.1 "Initial focus is set on the first input, which is the first focusable element." from https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

**Comment by catcarbonell** [comment]
Issue resolved on May 14th. Thanks for letting me know about accessibility issues!
